uploads = []
outputs = []

[[generated]]
id = "xUXmfG70cWiJcosuoWeHn"
uri = "file://artifacts/jbs-landing/public/hero-car.png"
type = "image"
title = "Front view luxury car"

[[generated]]
id = "bPrUDWGNAOaVHZXt8Hi8A"
uri = "file://artifacts/jbs-landing/public/showroom-car.png"
type = "image"
title = "Side profile luxury SUV"

[[generated]]
id = "hNQl7pJmnb36vz-nMCXxs"
uri = "file://artifacts/jbs-landing/public/interior-car.png"
type = "image"
title = "Luxury car interior"
